name: 'Code Quality Config'
description: 'Combined quality configuration. Copies standards files to repo.'
inputs:
  solutionPath:
    required: true
    description: 'The solution file.'
  codingStandardsRepo:
    required: true
    description: 'The coding standards repo to copy .editorconfig and DotSettings from.'
  gitHubCheckInToken: 
    required: true
    description: 'The personal access token for github to check in with. Cannot be default PAT or checkin will not occur.'
  gitHubActor: 
    required: true
    description: 'The nuget.config actor for nuget update.'
  gitHubArtifactToken: 
    required: true
    description: 'The personal access token for github to pull org nuget packages.'
runs:
  using: 'composite'
  steps:
    - name: Checkout Coding Standards
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.codingStandardsRepo }}
        token: ${{ inputs.gitHubCheckInToken }}
        path: ./coding-standards
    - name: Git Configure
      shell: bash
      run: |
        echo "GITHUB_TOKEN=${{ inputs.gitHubCheckInToken }}" >> $GITHUB_ENV
        git config --global user.name "Build Action"
        git config --global user.email "build@letsonboard.com"
    - name: Copy And Include Standards Files
      shell: bash
      run: |
        ./coding-standards/helper-scripts/copyStandardsFiles.sh ./C#/standardsFilesToCopy.txt ${{ inputs.solutionPath }}    
    - name: Ensure Git Ignore Contents
      shell: bash
      run: |
        ./coding-standards/helper-scripts/addGitIgnoreEntries.sh .gitignore .coding-standards/C#/cSharpGItIgnoreEntries.txt        
    